### ISSUE TITLE
Plugin not installing on Mac OS Sonoma 14.0

### ISSUE THREAD

**Issue by Joehl1103** [dubisdev/cerebro-todoist#19] opened 2023-11-09 14:59 UTC
Hello!

Super excited about getting this plugin to work! See below for what happens when I try to install, though:

[see here](https://github.com/dubisdev/cerebro-todoist/assets/73568630/4129410a-ec3a-402d-b83d-e4c5a2ca343e)

Sincerely,
Joseph

**Comment by dubisdev** [comment] 2023-11-09 15:05
Hi @Joehl1103 

Could you please open the developer tools of Cerebro to see what's going wrong?

To do this:

1. Write "Settings" in Cerebro
2. Activate the developer mode
3. Go to the tray icon and select developer tools.
4. Once opened, try to install the plugin
5. Take a screenshot of the devtools and share it here so I can see what's going wrong :)

**Comment by Joehl1103** [comment] 2023-11-09 23:33
Thanks for getting back to me. Here you go:
![Uploading Screenshot 2023-11-09 at 5.32.27 PM.png…]()

**Comment by dubisdev** [comment] 2023-11-10 00:06
Great! Thank you.

I think I know what to do :) (the problem is related to the @cerebroapp/cerebro-ui dependency)

If I have some time tomorrow I'll publish an update.

**Comment by Joehl1103** [comment] 2023-11-10 14:43
Thank you!

**Comment by Joehl1103** [comment] 2023-11-10 20:00
FWIW, this seems to be happening on both of my macbook air's, both running Sonoma 14.0, and for all plugins, not just todoist.

**Comment by dubisdev** [comment] 2023-11-11 09:58
Hi @Joehl1103, could you please tell me the Cerebro version you are using?

You can get that by typing "version" in Cerebro

**Comment by dubisdev** [comment] 2023-11-11 10:23
Hi again @Joehl1103
Just published a new version for the plugin (v2.8.3)

Please give it a try and tell me if it is working now. Then I'll close this issue


Some other plugins might also have this error because of the `cerebro-ui` dependency. It was solved here https://github.com/cerebroapp/cerebro-ui/commit/b20a5b8d2b54651ea908dbe8b96e7fe032a0fa0b But some plugins hasn't been updated for years.

**Comment by Joehl1103** [comment] 2023-11-13 23:24
Thank you! I was able to install, but now I get the following error message when trying to run the shortcuts:
<img width="644" alt="Screenshot 2023-11-13 at 5 23 44 PM" src="https://github.com/dubisdev/cerebro-todoist/assets/73568630/165811de-15fd-4c51-9784-ee8ab0104fbb">

**Comment by dubisdev** [comment] 2023-11-14 06:54
Hi @Joehl1103

I'm glad you managed to install it.

That's totally normal. You must set an API token from todoist in the plugin settings so the app can connect to your todoist account.

You can get this token from the "Integrations" section in the settings of Todoist web/Desktop. Then copy it to the plugin settings:

![169042136-e94d61a0-9bac-4992-80f3-0c62396a616d.png](https://github.com/dubisdev/cerebro-todoist/assets/77246331/914bbae4-3be5-4656-87d8-7fd2488d3341)

I'm closing this PR as the error is solved.

Feel free to open a new issue if you find problems with this :)

Thank you!

**Closed** 2023-11-14 06:55 UTC

**Comment by Joehl1103** [comment] 2023-11-14 15:50
Thank you for your help!
